import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Privacy Policy",
    description: "How SmartDeskHub collects, uses, and protects your personal information.",
};

export default function PrivacyPolicyPage() {
    return (
        <article className="prose-legal">
            <h1 className="font-serif text-headline-md font-semibold text-primary mb-sm">
                Privacy Policy
            </h1>
            <p className="font-label-sm text-label-sm text-on-surface-variant mb-xxl">
                Last updated: 30 May 2026
            </p>

            <Section title="1. Who We Are">
                <p>
                    SmartDeskHub (&ldquo;we&rdquo;, &ldquo;our&rdquo;, &ldquo;us&rdquo;) operates
                    the website at smartdeskhub.in (the &ldquo;Site&rdquo;). We are the data
                    controller for personal information collected through this Site. Registered
                    address: SmartDeskHub Technologies Pvt. Ltd., Bengaluru, Karnataka, India.
                </p>
            </Section>

            <Section title="2. Information We Collect">
                <p>We collect information you give us directly and information generated by your use of the Site.</p>
                <h3>Information you provide</h3>
                <ul>
                    <li><strong>Account data</strong> — name and email address when you create an account.</li>
                    <li><strong>Order data</strong> — name, shipping address, phone number, and payment details when you place an order.</li>
                    <li><strong>Communications</strong> — messages you send to our support team.</li>
                    <li><strong>Newsletter</strong> — email address if you subscribe to our mailing list.</li>
                </ul>
                <h3>Information collected automatically</h3>
                <ul>
                    <li><strong>Usage data</strong> — pages visited, products viewed, time on site, and referring URLs.</li>
                    <li><strong>Device data</strong> — IP address, browser type, operating system.</li>
                    <li><strong>Cookies</strong> — see our <a href="/legal/cookies">Cookie Policy</a> for full details.</li>
                </ul>
            </Section>

            <Section title="3. How We Use Your Information">
                <ul>
                    <li>To process and fulfil your orders, including sending order confirmations and shipping updates.</li>
                    <li>To create and manage your account.</li>
                    <li>To respond to your support enquiries.</li>
                    <li>To send you marketing emails where you have opted in (you can unsubscribe at any time).</li>
                    <li>To improve the Site — analysing usage patterns to fix bugs and build better features.</li>
                    <li>To comply with legal obligations, including tax and consumer protection law.</li>
                    <li>To detect and prevent fraud.</li>
                </ul>
            </Section>

            <Section title="4. Legal Bases for Processing (GDPR / Indian DPDP Act)">
                <p>Where applicable law requires a legal basis, we process your data on the following grounds:</p>
                <ul>
                    <li><strong>Contract</strong> — processing necessary to fulfil an order you placed.</li>
                    <li><strong>Legitimate interests</strong> — fraud prevention, site analytics, improving our services.</li>
                    <li><strong>Consent</strong> — marketing emails and non-essential cookies. You can withdraw consent at any time.</li>
                    <li><strong>Legal obligation</strong> — tax records and compliance reporting.</li>
                </ul>
            </Section>

            <Section title="5. Sharing Your Information">
                <p>We do not sell your personal information. We share it only with:</p>
                <ul>
                    <li><strong>Payment processors</strong> (e.g. Razorpay) — to handle transactions securely.</li>
                    <li><strong>Logistics partners</strong> — to deliver your order.</li>
                    <li><strong>Email service providers</strong> — to send transactional and marketing emails.</li>
                    <li><strong>Analytics providers</strong> — aggregated, anonymised usage data.</li>
                    <li><strong>Law enforcement</strong> — when required by a valid legal request.</li>
                </ul>
                <p>All third-party processors are contractually bound to protect your data and use it only for the specified purpose.</p>
            </Section>

            <Section title="6. Data Retention">
                <p>
                    We retain order data for 7 years to comply with Indian tax law. Account data
                    is retained until you request deletion. Marketing preferences are retained until
                    you unsubscribe. Anonymised analytics data may be retained indefinitely.
                </p>
            </Section>

            <Section title="7. Your Rights">
                <p>Depending on your jurisdiction, you have the right to:</p>
                <ul>
                    <li><strong>Access</strong> — request a copy of the personal data we hold about you.</li>
                    <li><strong>Rectification</strong> — correct inaccurate or incomplete data.</li>
                    <li><strong>Erasure</strong> — request deletion of your data where there is no legal basis to retain it.</li>
                    <li><strong>Portability</strong> — receive your data in a machine-readable format.</li>
                    <li><strong>Object</strong> — opt out of processing based on legitimate interests.</li>
                    <li><strong>Withdraw consent</strong> — for any processing based on consent, at any time.</li>
                </ul>
                <p>
                    To exercise any of these rights, email us at{" "}
                    <a href="mailto:privacy@smartdeskhub.in">privacy@smartdeskhub.in</a>. We will respond
                    within 30 days.
                </p>
            </Section>

            <Section title="8. Cookies">
                <p>
                    We use cookies and similar technologies. See our dedicated{" "}
                    <a href="/legal/cookies">Cookie Policy</a> for the full list of cookies we use
                    and how to manage them.
                </p>
            </Section>

            <Section title="9. Security">
                <p>
                    We use industry-standard security measures including HTTPS encryption, access
                    controls, and regular security reviews. No method of transmission over the
                    internet is completely secure; we cannot guarantee absolute security but we take
                    reasonable precautions.
                </p>
            </Section>

            <Section title="10. Children">
                <p>
                    This Site is not directed at children under 13. We do not knowingly collect
                    personal data from children. If you believe we have inadvertently collected data
                    from a child, please contact us immediately and we will delete it.
                </p>
            </Section>

            <Section title="11. Changes to This Policy">
                <p>
                    We may update this Privacy Policy from time to time. We will post the revised
                    policy on this page with an updated &ldquo;Last updated&rdquo; date. For
                    material changes, we will notify registered users by email.
                </p>
            </Section>

            <Section title="12. Contact">
                <p>
                    Questions about this policy? Contact our Data Protection team at{" "}
                    <a href="mailto:privacy@smartdeskhub.in">privacy@smartdeskhub.in</a> or write to
                    SmartDeskHub Technologies Pvt. Ltd., Bengaluru, Karnataka, India.
                </p>
            </Section>
        </article>
    );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <section className="mb-xl">
            <h2 className="font-serif text-[1.25rem] font-semibold text-primary mb-md leading-snug">
                {title}
            </h2>
            <div className="space-y-sm font-body-md text-on-surface-variant leading-relaxed [&_h3]:font-semibold [&_h3]:text-primary [&_h3]:mt-md [&_h3]:mb-xs [&_ul]:pl-md [&_ul]:space-y-xs [&_ul]:list-disc [&_a]:text-secondary [&_a]:underline [&_a]:underline-offset-4 [&_a:hover]:opacity-70">
                {children}
            </div>
        </section>
    );
}
